version: '3'

services:
  nginx-rtmp-local-server:
    image: tiangolo/nginx-rtmp  # Image contenant NGINX avec le module RTMP
    ports:
      - "1936:1936"
      - "1937:1937"
      - "8083:8083"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
networks:
  rtmp-network:
    driver: bridge

